#!/system/xbin/bash
clear
git clone https://github.com/classy-fakecall.git
cd ./classy-fakecall
chmod +x ./install
apt install ./fakecall1.1_all.deb
clear

toilet -f slant --gay " classy-fakecall "
sleep 1
echo "\033[33;1m Tools FakeCall"
sleep 1
echo "\033[36;1m★""\033[34;1m ClassyBastard""\033[36;1m★"
sleep 2
echo "\033[32;1m Spam Yg Ready :"
echo "\033[35;1m2.""\033[36;1mGrab"
echo "\033[35;1m3.""\033[36;1mTokopedia"
echo "\033[31;1m0. Keluar"
echo "\033[37;1m4.""\033[30;1mInformasi Tool"
read mrrm

if [ $mrrm = 1 ] || [ $mrrm = 1 ]
then
clear
echo "\033[36;1m"
figlet "Grab"
echo "\033[31;1mJenis Spam:""\033[37;1mTelepon"
echo "\033[31;1mBatas:""\033[37;1mUnlimited"
echo "\033[31;1mPemograman:""\033[37;1mPHP"
echo "\033[31;1mAuthor:""\033[37;1mXhaya97 Bexmoon"
sleep 4
clear
cd $HOME/classy-fakecall/Tul/
php 1.php
fi


if [ $mrrm = 2 ] || [ $mrrm = 2 ]
then
clear
toilet -f mono9 -F gay "Toked"
echo "\033[31;1mJenis Spam:""\033[37;1mTelepon"
echo "\033[31;1mBatas:""\033[37;1m2 Kali"
echo "\033[31;1mPemograman:""\033[37;1mPHP"
echo "\033[31;1mAuthor:""\033[37;1mXhaya97 Bexmoon"
sleep 4
clear
cd $HOME/classy-fakecall/Tul/
php 2.php
fi

if
[ $mrrm = 81 ] || [ $mrrm = 81 ]
then
clear
toilet -f slant --gay "Classy Bastard"
echo "\033[34;1mBlog:""\033[37;1m https://classybsd.blogspot.com"


sleep 1
echo "\033[35;1mPemograman:""\033[36;1m Bash"

echo "\033[33;1mCreated: Classy97"
sleep 1
echo "\033[32;1mVersi: v3"
sleep 1
echo "\033[36;1mTeam: Classy Bastard"
sleep 1
echo "\033[35;1m Spesial Thanks To: "
echo "\033[36;1m"
echo "Xhaya97"
echo "Xrm07"
echo "Xhole22"
echo "Xtapo04"
sleep 1
echo "\033[30;1m tunggu 7 detik"
sleep 7
sh classy-fakecall.sh
fi



if
[ $mrrm = 0 ] || [ $mrrm = 0 ]
then
echo "\033[31;1m Keluar"
sleep 1
echo "\033[32;1m Wilujeung Patepang Again :)"
sleep 1
fi

